#!/bin/bash
# Author: Kent Chadwick
# Description: Allows user to search the BusinessDetails file for records matching their search term
#
# Count the number of entries that match the user's search input, and store the value in $inputCount
inputCount=$(grep -ci $1 BusinessDetails)

# Display different options depending on the value of $inputCount
if [ $inputCount -eq 0 ]
then
	echo "Your search didn't match any records in our address book."
	read -p "Would you like to perform another search? (y/n)" ans1
	if [[ $ans1 == y* || $ans1 == Y* ]]
	then
		echo
		read -p "Please enter your search stuff" find
		echo
		./FindBiz $find
	else
		echo
		echo "Good bye!"
		echo
		exit 0
	fi
elif [ $inputCount -gt 1 ]
then
	echo "Your search matched multiple records."
	echo
	subMenu1=true
	while [ "$subMenu1" == true ]; do	# Menu will reload until user enters valid input
		echo "Would you like to view one of these records?"
		echo "~~~~~~~~~~~~~~~~~~~~"
		# While loop to create numbered menu based on the number of entries returned by the user search
		count=1
		while [ $count -le $inputCount ]; do
			menuLine=$(grep -i $1 BusinessDetails | sed -n "${count}p")
			newL=$'\n'
			menuLines+="$count) $menuLine$newL"
			selectFrom+="count$count $menuLine$newL"
			((count++))
		done
		echo "$menuLines" | column -t -s $'\t' -n
		echo "~~~~~~~~~~~~~~~~~~~~"
		mainMenOption=$(($inputCount + 1))
		echo "$mainMenOption) Return to Main Menu"
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "0) Exit"
	        echo "~~~~~~~~~~~~~~~~~~~~"
		read -p "Menu choice: " choice
		if [ $choice -eq  $mainMenOption ] 2> /dev/null
		then
			subMenu1=false
			./Menu
		elif [ $choice -eq 0 ] 2> /dev/null
		then
			subMenu1=false
			echo
			echo "Goodbye!"
			echo
			exit 0
		elif [ $choice -lt $mainMenOption ] 2> /dev/null
		then
			subMenu1=false
			echo
			echo "~~~~~~~~~~~~~~~~~~~~"
			echo
			if [ $choice -lt 10 ]; then
				singleResult=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$choice" | cut -c 8-)
				echo $singleResult
			elif [ $choice -lt 100 ]; then
				singleResult=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$choice" | cut -c 9-)
				echo $singleResult
			else
				singleResult=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$choice" | cut -c 10-)
				echo $singleResult
			fi
			echo
			echo "~~~~~~~~~~~~~~~~~~~~"
			echo "1) Update Contact"
			echo "~~~~~~~~~~~~~~~~~~~~"
			echo "2) Return to Main Menu"
			echo "~~~~~~~~~~~~~~~~~~~~"
			echo "0) Exit"
			echo "~~~~~~~~~~~~~~~~~~~~"
			read -p "Enter Menu Choice: " choice1

			case $choice1 in
			1)	echo
				echo "Which field would you like to update?"
				echo
				echo singleResultMenu="$singleResult + 'Business Name\tContact Name\tAddress\tPhone Number\tEmail Address\n---\t---\t---\t---\t---'"
				echo $singleResultMenu
				echo
				echo "~~~~~~~~~~~~~~~~~~~~"
				echo "1) Business Name"
				echo "2) Contact Name"
				echo "3) Address"
				echo "4) Phone Number"
				echo "5) Email Address"
				echo "~~~~~~~~~~~~~~~~~~~~"
				echo "6) Return to Main Menu"
				echo "~~~~~~~~~~~~~~~~~~~~"
				echo "0) Exit"
				echo "~~~~~~~~~~~~~~~~~~~~"
				read -p "Enter Menu Choice: " choice2

				case $choice2 in
				1)	echo
					read -p "Please enter the Business Name: " newBizName
					toReplace=$(echo $singleResult | awk -F "\n" '{print $1}')
					grep "$toReplace" BusinessDetails | sed 's/"$toReplace"/"$newBizName"'
					echo
					echo "Business Updated."
					echo
					;;
				2)
					;;
				3)
					;;
				4)
					;;
				5)
					;;
				6)
					;;
				0)
					;;
				*)
					;;
				esac
				;;
			2)	./Menu
				;;
			0)	echo
				echo "Goodbye!"
				echo
				exit 0
				;;
			*)	echo
				echo "Invalid input. Please enter a number between 0 and 2."
				echo
				;;
			esac
		else
			echo
			echo "Ivalid input. Please enter a number between 0 and $mainMenOption."
			echo
			menuLines=""
			selectFrom=""
		fi
	done	# Close the while loop for the sub-menu
else
	echo
	echo "Your search matched the following record."
	echo
fi
