#!/bin/bash
# Author: Kent Chadwick
# Description: Menu system to drive the business contact script
#
echo
echo Welcome $USER
echo "~~~~~~~~~~~~~~~~~~~~"
echo " M A I N    M E N U "
echo "~~~~~~~~~~~~~~~~~~~~"
echo "1) Add a new Business"
echo "2) Remove an existing Business"
echo "3) Search for a Business"
echo "4) Email Business(es)"
echo "~~~~~~~~~~~~~~~~~~~~"
echo "0) Exit"
echo "~~~~~~~~~~~~~~~~~~~~"
read -p "Menu choice: " option

case $option in
1)	# Read in user input for business details and pass the variables to the AddBiz script as arguments
	echo
	echo "Please enter the business name: "
	read bizName
	nameMenu=true
	while [ $nameMenu == true ]; do # while loop to control validation of input
		if [ -z "$bizName" ]; then # checks for empty string
			echo
                        echo "No text entered. Please enter the business name again: "
                        read bizName
		else
			nameMenu=false # break the loop, as input is valid
		fi
	done
	echo
	echo "Please enter the contact person's name: "
	read contactName
        contactMenu=true
        while [ $contactMenu == true ]; do # while loop to control validation of input
                if [ -z "$contactName" ]; then # checks for empty string
                        echo
                        echo "No text entered. Please enter the contact's name again: "
                        read contactName
                else
                        contactMenu=false # break the loop, as input is valid
                fi
        done
	echo
	echo "Please enter the business address: "
	read bizAddress
        addressMenu=true
        while [ $addressMenu == true ]; do # while loop to control validation of input
                if [ -z "$bizAddress" ]; then # checks for empty string
                        echo
                        echo "No text entered. Please enter the address again: "
                        read bizAddress

                else
                        addressMenu=false # break the loop, as input is valid

                fi
        done
	echo
	echo "Please enter the contact person's phone number: "
	read contactNum
        numMenu=true
	phoneRegEx="\b[0-9._+-]{3,16}\b" # regex for phone patterns
	while [ $numMenu == true ]; do # while loop to control validation of input
                if [ -z "$contactNum" ]; then # checks for empty string
                        echo
                        echo "No number entered. Please enter the contact number: "
                        read contactNum
                elif [[ $contactNum =~ $phoneRegEx ]]; then # check for phone number format
                        numMenu=false # break the loop, as input is valid
		else
	                echo
                        echo "Invalid entry. Phone number must be between 3 and 15 characters,"
                        echo "and contain only numbers or the following symbols: . _ - +"
                        echo
                        echo "Please enter the contact person's phone number: "
                        read contactNum
                fi
        done
	echo
	echo "Please enter contact person's email address: "
	read contactEmail
        emailRegEx="\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" # regex for email patterns
        emailMenu=true
        while [ $emailMenu == true ]; do
                if [[ $contactEmail =~ $emailRegEx ]]; then
                        emailMenu=false # break the loop, as input is valid
                else
                        echo
                        echo "Invalid email address entered. Please enter the email address again: "
                        read contactEmail
                fi
        done
	echo
	# pass the variables to the AddBiz script as arguments
	./AddBiz "$bizName" "$contactName" "$bizAddress" "$contactNum" "$contactEmail"
	echo
	./Menu
	;;
2)	# Run a sub-menu for removing a business. It is enclosed in a while loop
	# to allow it to be reloaded repeatedly if the user's input is invalid.
	menu=true
	while [ $menu == true ]
	do
		echo
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "R E M O V E  M E N U"
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "1) Remove record by business name"
		echo "2) Remove record by contact name"
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "3) Return to main menu"
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "0) Exit"
		echo "~~~~~~~~~~~~~~~~~~~~"
		read -p "Menu choice: " option2

		case $option2 in
		1)	echo
			echo "Please enter the Business name: "
			read bizName
			echo
			./RmBiz 1 $bizName
			;;
		2)	echo
			echo "Please enter the Contact name: "
			read contactName
			echo
			./RmBiz 2 $contactName
			;;
		3)	# Re-run the Menu script
			./Menu
			;;
		0)	#
			menu=false # This allows the script to exit the while loop
			echo
			echo "Goodbye!"
			echo
			exit 0
			;;
		*)	# Catches any invalid user input
			echo
			echo "Invalid input. Please enter a number between 0 & 3."
			;;
		esac
	done
	;;
3)	echo
        echo "Please enter the business name, number, address, email, etc: "
        read find
	findMenu=true
	while [ $findMenu == true ]; do # loop to validate entry
		if [ -z "$find" ]; then # checks for empty string
                        echo
                        echo "No text entered. Please enter something to search for: "
                        read find
                else
                        findMenu=false # break the loop, as input is valid
                fi
	done
	./FindBiz $find
	;;
4)	# Run a sub-menu for emailing contacts. It is enclosed in a while loop
        # to allow it to be reloaded repeatedly if the user's input is invalid.
        menu=true
        while [ $menu == true ]
        do
		echo
		echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "E M A I L    M E N U"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "1) Search for business to email"
		echo "2) Email all businesses"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "3) Return to main menu"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "0) Exit"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        read -p "Menu choice: " option3

	        case $option3 in

		1)	subMenu=true
			while [ $subMenu == true ]; do # loop to control the search results menu
			echo
			echo "Please enter the business name, contact name, email address, etc: " # read in search term(s)
			read search
			matches=$(grep -i "$search" BusinessDetails) # returns records with a matching string
			inputCount=$(echo "$matches" | grep -ci "$search") # count results from grep and store in variable

			if [ $inputCount -gt 1 ]; then # if there are multiple matches
				echo
				echo "Your search returned $inputCount records."
				echo
				echo "Would you like to email one of these businesses?"
		                echo "~~~~~~~~~~~~~~~~~~~~"
		                # While loop to create numbered menu based on the number of entries returned by the user search
		                count=1 # variable to increment up to value of $inputCount
		                while [ $count -le $inputCount ]; do
		                        menuLine=$(echo "$matches" | sed -n "${count}p") # stores individual record in menuLine variable
		                        newL=$'\n' # line break variable to use below
		                        menuLines+="$count) $menuLine$newL" # concats numbered menu lines w/ line breaks
		                        selectFrom+="count$count $menuLine$newL" # creates separate list with "count" term at start to make selection of the correct line more robust
		                        ((count++)) # increments count variable
		                done
				# create heading for menu
		                resultMenu=$'Business Name\tContact Name\tAddress\tPhone Number\tEmail Address\n----------\t---------\t----------\t----------\t----------\n'
                                resultMenu+="$menuLines"
				echo "$resultMenu" | column -t -s $'\t' -n # displays options w/ column layout
		                echo "~~~~~~~~~~~~~~~~~~~~"
				emailAll=$(($inputCount + 1))
				echo "$emailAll) Email all of the above"
				echo "~~~~~~~~~~~~~~~~~~~~"
		                mainMenOption=$(($inputCount + 2)) # Return to main menu value dynamically created
		                echo "$mainMenOption) Return to Main Menu"
		                echo "~~~~~~~~~~~~~~~~~~~~"
		                echo "0) Exit"
		                echo "~~~~~~~~~~~~~~~~~~~~"
		                read -p "Menu choice: " choice

				if [ $choice -eq  $mainMenOption ] 2> /dev/null # return to main menu
		                then
		                        subMenu=false
		                        ./Menu
		                elif [ $choice -eq 0 ] 2> /dev/null # exit
		                then
		                        subMenu=false
		                        echo
		                        echo "Goodbye!"
		                        echo
		                        exit 0
				elif [ $choice -eq $emailAll ] 2> /dev/null # email all records returned from search
				then
					echo
                                        echo "Please enter the email subject line: "
                                        read subject
                                        echo
                                        echo "Please enter the email message: "
                                        read message
					echo
					echo "Are you sure you want to send this message to these $inputCount contacts?"
		                        echo
		                        echo "SUBJECT: $subject"
		                        echo "----------"
		                        echo "MESSAGE: $message"
					echo
					read -p "(y/n): " sure
					echo
					if [[ $sure == y* || $sure == Y* ]]; then
						count=1
						# loop to read in each line from search results and send that contact an email
						while [ $count -le $inputCount ]; do
							if [ $inputCount -lt 10 ]; then # accounting for possible different lengths of the prefix which needs to be cut from the string
		                                                chosenEntry=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$count")
		                                        elif [ $inputCount -lt 100 ]; then
		                                                chosenEntry=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$count")
		                                        else
		                                                chosenEntry=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$count")
		                                        fi
							# retrieve the email address from the entry
							emailAddress=$(echo "$chosenEntry" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
	                                                echo "$message" | mail -s $subject $emailAddress 2> /dev/null
	                                                ((count++))
						done
						echo
						echo "Messase sent to $inputCount contacts."
						echo
						subMenu=false
						./Menu
					else
						echo
                                                echo "Would you like to perform another search? (y/n): "
                                                read ans4
                                                echo
                                                if [[ $ans4 == y* || $ans4 == Y* ]]; then
                                                        subMenu=true
							# previous results are cleared to allow ner search
							menuLines=""
							selectFrom=""
							resultMenu=""
                                                else
                                                        subMenu=false
                                                        echo
                                                        echo "Would you like to return to the main menu? (y/n): "
                                                        read ans5
                                                        echo
                                                        if [[ $ans5 == y* || $ans5 == Y* ]]; then
                                                                ./Menu
                                                        else
                                                                echo
                                                                echo "Goodbye!"
                                                                echo
                                                                exit 0
                                                        fi
                                                fi
                                        fi
				elif [ $choice -lt $emailAll ] 2> /dev/null # if there is a single entry selected from the results
			        then
				chosenToEmail=true
				while [ $chosenToEmail == true ]; do
		                        echo
		                        echo "Is this the business you would like to email?"
		                        echo
					# create header for result display
					resultMenu=$'Business Name\tContact Name\tAddress\tPhone Number\tEmail Address\n----------\t---------\t----------\t----------\t----------\n'
		                        if [ $choice -lt 10 ]; then # account for prefix length to be cut
		                                chosenEntry=$(echo "$selectFrom" | grep "count$choice" | cut -c 8-)
		                                resultMenu+="$chosenEntry"
						echo "$resultMenu" | column -t -s $'\t' -n # display column layout
		                        elif [ $choice -lt 100 ]; then
		                                chosenEntry=$(echo "$selectFrom" | grep "count$choice" | cut -c 9-)
		                                resultMenu+="$chosenEntry"
                                                echo "$resultMenu" | column -t -s $'\t' -n
		                        else
		                                chosenEntry=$(echo "$selectFrom" | grep "count$choice" | cut -c 10-)
		                                resultMenu+="$chosenEntry"
                                                echo "$resultMenu" | column -t -s $'\t' -n
		                        fi
					echo
					read -p "(y/n): " sureEmail

					if [[ $sureEmail == y* || $sureEmail == Y* ]]; then
						#retrieve email from the entry
						emailAddress=$(echo "$chosenEntry" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
						echo
						echo "Please enter the email subject line: "
						read subject
						echo
						echo "Please enter the email message: "
						read message
						echo
						echo "Are you sure you want to send this message to $emailAddress?"
	                                        echo
	                                        echo "SUBJECT: $subject"
	                                        echo "----------"
	                                        echo "MESSAGE: $message"
	                                        echo
						read -p "(y/n): " sure
						if [[ $sure == y* || $sure == Y* ]]; then
							echo "$message" | mail -s $subject $emailAddress
							echo
							echo "Message sent to $emailAddress."
							echo
							menu=false
							subMenu=false
							chosenToEmail=false
							./Menu
						else
							chosenToEmail=false
							menuLines=""
                                                        selectFrom=""
                                                        resultMenu=""
						fi
						subMenu=false
	                        	else
	                                	echo
	                                	echo "Would you like to perform another search? (y/n): "
						read ans4
	                                	echo
						if [[ $ans4 == y* || $ans4 == Y* ]]; then
							chosenToEmail=false
							menuLines=""
							selectFrom=""
							resultMenu=""
						else
							subMenu=false
							chosenToEmail=false
							echo
							echo "Would you like to return to the main menu? (y/n): "
							read ans5
							echo
							if [[ $ans5 == y* || $ans5 == Y* ]]; then
								menu=false
								./Menu
							else
								menu=false
								echo
								echo "Goodbye!"
								echo
								exit 0
							fi
						fi
					fi
				done
				else
					echo
		                        echo "Invalid input. Please enter a number between 0 & $mainMenuOption."
                		        echo
				fi
			elif [ $inputCount -eq 1 ]; then # when the search only returns one result
	                        chosenToEmail=true
				while [ $chosenToEmail == true ]; do
				echo
				echo "Your search returned the following record."
				echo
				echo "Would you like to email this business?"
				echo "~~~~~~~~~~~~~~~~~~~~"
	                        echo
				# header for results display
	                        singleResultMenu=$'Business Name\tContact Name\tAddress\tPhone Number\tEmail Address\n----------\t---------\t----------\t----------\t----------\n'
	                        singleResultMenu+="$matches" # add results to display
	                        echo "$singleResultMenu" | column -t -s $'\t' -n # display in column format
				echo
                                read -p "(y/n): " sureEmail

                                if [[ $sureEmail == y* || $sureEmail == Y* ]]; then
                                        	# retrieve email from entry
						emailAddress=$(echo "$matches" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
                                          	echo
                                                echo "Please enter the email subject line: "
                                                read subject
                                                echo
                                                echo "Please enter the email message: "
                                                read message
                                                echo
                                                echo "Are you sure you want to send this message to $emailAddress?"
                                                echo
                                                echo "SUBJECT: $subject"
                                                echo "----------"
                                                echo "MESSAGE: $message"
                                                echo
                                                read -p "(y/n): " sure
                                                if [[ $sure == y* || $sure == Y* ]]; then
                                                        echo "$message" | mail -s $subject $emailAddress # send the email
                                                        echo
                                                        echo "Message sent to $emailAddress."
                                                	echo
							menu=false
							subMenu=false
							chosenToEmail=false
							./Menu
                                                else
                                                        chosenToEmail=false
                                                fi
                                        menu=false
					subMenu=false
					./Menu
				else
					echo
                                        echo "Would you like to perform another search? (y/n): "
                                        read ans4
                                        echo
                                        if [[ $ans4 == y* || $ans4 == Y* ]]; then
                                                subMenu=true
						chosenToEmail=false
                                        else
                                                subMenu=false
						chosenToEmail=false
                                                echo
                                                echo "Would you like to return to the main menu? (y/n): "
                                                read ans5
                                                echo
                                                if [[ $ans5 == y* || $ans5 == Y* ]]; then
                                                        menu=false
							./Menu
                                                else
							menu=false
                                                        echo
                                                        echo "Goodbye!"
                                                        echo
                                                        exit 0
                                                fi
                                        fi
				fi
				done
			else
                                echo
				echo "Your search didn't return any results."
				echo
                                echo "Would you like perform another search? (y/n): "
                                read ans5
                                echo
                                if [[ $ans5 == y* || $ans5 == Y* ]]; then
                                        subMenu=true
                                else
					subMenu=false
					echo
                                        echo "Would you like to return to the main menu? (y/n): "
	                                read ans5
        	                        echo
                	                if [[ $ans5 == y* || $ans5 == Y* ]]; then
                        	                menu=false
						./Menu
                                	else
						menu=false
                                        	echo
	                                        echo "Goodbye!"
        	                                echo
                	                        exit 0
                        	        fi

                                fi
			fi
			done
			;;
		2)	# emailing the whole address book
			echo
			echo "Please enter the email subject line: "
                        read subject
                        echo
                        echo "Please enter the email message: "
                        read message
                        echo
			echo "Are you sure you want to send this message to all your contacts?"
			echo
			echo "SUBJECT: $subject"
			echo "----------"
			echo "MESSAGE: $message"
			echo
			read -p "(y/n): " sureEmail
			if [[ $sureEmail == y* || $sureEmail == Y* ]]; then
				bizNum=$(wc -l < BusinessDetails)
				count=1
				while [ $count -le $bizNum ]; do # loop to retrieve indivisual email asddresses and send the email to each one.
					emailAddress=$(sed -n "${count}p" BusinessDetails | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
					echo "$message" | mail -s $subject $emailAddress 2> /dev/null # dumps errors for invalid email addresses
					((count++))
				done
				echo
                        	echo "Message sent to all contacts."
                        	echo
                        	menu=false
                        	./Menu
			else
				subMenu=false
                                echo
                                echo "Would you like to return to the main menu? (y/n): "
                                read ans5
                                echo
                                if [[ $ans5 == y* || $ans5 == Y* ]]; then
                                        menu=false
                                        ./Menu
                                else
                                        menu=false
                                        echo
                                        echo "Goodbye!"
                                        echo
                                        exit 0
                                fi
			fi
			;;
		3) 	menu=false
			./Menu
			;;
		0)	menu=false
			echo
			echo "Goodbye!"
			echo
			exit 0
			;;
		*)	echo
	        	echo "Invalid input. Please enter a number between 0 & 4."
			echo
			;;
		esac
	done
	;;
0)	addMenu=false
	nameMenu=false
	contactMenu=false
	addressMenu=false
	numMenu=false
	emailMenu=false
	menu=false
	echo
	echo "Goodbye!"
	echo
	exit 0
	exit 0
	;;
*)	echo
        echo "Invalid input. Please enter a number between 0 & 4."
	echo
	./Menu
	;;
esac

exit 0
