#!/bin/bash
# Author: Kent Chadwick
# Description: Menu system to drive the business contact script
#
# command to select email address(es) from file: grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" BusinessDetails
echo
echo Welcome $USER
echo "~~~~~~~~~~~~~~~~~~~~"
echo " M A I N    M E N U "
echo "~~~~~~~~~~~~~~~~~~~~"
echo "1) Add a new Business"
echo "2) Remove an existing Business"
echo "3) Search for a Business"
echo "4) Email Business(es)"
echo "~~~~~~~~~~~~~~~~~~~~"
echo "0) Exit"
echo "~~~~~~~~~~~~~~~~~~~~"
read -p "Menu choice: " option

case $option in
1)	# Read in user input for Business details and pass the variables to the AddBiz script as arguments
	echo
	echo "Please enter the business name: "
	read bizName
	nameMenu=true
	while [ $nameMenu == true ]; do # while loop to control validation of input
		if [ -z "$bizName" ]; then # checks for empty string
			echo
                        echo "No text entered. Please enter the business name again (0 to return to main menu): "
                        read bizName
			if [ $bizName -eq 0 ] 2> /dev/null # checks for entry of 0
                        then 
                                nameMenu=false
                                ./Menu
                        fi
		else
			nameMenu=false
		fi
	done
	echo
	echo "Please enter the contact person's name: "
	read contactName
        contactMenu=true
        while [ $contactMenu == true ]; do # while loop to control validation of input
                if [ -z "$contactName" ]; then # checks for empty string
                        echo
                        echo "No text entered. Please enter the contact's name again (0 to return to main menu): "
                        read contactName
			if [ $contactName -eq 0 ] 2> /dev/null # checks for entry of 0
                        then 
				contactMenu=false
                                ./Menu
                        fi
                else
                        contactMenu=false
                fi
        done
	echo
	echo "Please enter the business address: "
	read bizAddress
        addressMenu=true
        while [ $addressMenu == true ]; do # while loop to control validation of input
                if [ -z "$bizAddress" ]; then # checks for empty string
                        echo
                        echo "No text entered. Please enter the address again (0 to return to main menu): "
                        read bizAddress
			if [ $bizAddress -eq 0 ] 2> /dev/null # checks for entry of 0
			then
				addressMenu=false
				./Menu
			fi
                else
                        addressMenu=false
                fi
        done
	echo
	echo "Please enter the contact person's mobile number: "
	read contactNum
        numMenu=true
        while [ $numMenu == true ]; do # while loop to control validation of input
                if [ -z "$contactNum" ]; then # checks for empty string
                        echo
                        echo "No number entered. Please enter the contact number (0 to return to main menu): "
                        read contactNum
                        if [ $contactNum -eq 0 ] 2> /dev/null # checks for entry of 0
                        then
                                numMenu=false
                                ./Menu
                        fi
                else
                        numMenu=false
                fi
        done
	echo
	echo "Please enter contact person's email address: "
	read contactEmail
        emailRegEx="\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b"
        emailMenu=true
        while [ $emailMenu == true ]; do
                if [[ $contactEmail =~ $emailRegEx ]]; then
                        emailMenu=false
                else
                        echo
                        echo "Invalid email address entered. Please enter the email address again (0 to return to main menu): "
                        read contactEmail
			if [ $contactEmail -eq 0 ] 2> /dev/null # checks for entry of 0
                        then
                                numMenu=false
                                ./Menu
                        fi
                fi
        done
	echo
	./AddBiz "$bizName" "$contactName" "$bizAddress" "$contactNum" "$contactEmail"
	echo
	echo "New Business - \"$bizName\" - added."
	echo
	./Menu
	;;
2)	# Run a sub-menu for removing a business. It is enclosed in a while loop
	# to allow it to be reloaded repeatedly if the user's input is invalid.
	menu=true
	while [ $menu == true ]
	do
		echo
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "R E M O V E  M E N U"
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "1) Remove record by business name"
		echo "2) Remove record by contact name"
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "3) Return to main menu"
		echo "~~~~~~~~~~~~~~~~~~~~"
		echo "0) Exit"
		echo "~~~~~~~~~~~~~~~~~~~~"
		read -p "Menu choice: " option2

		case $option2 in
		1)	echo
			read -p "Please enter the Business name: " bizName
			echo
			./RmBiz 1 $bizName
			;;
		2)	echo
			read -p "Please enter the Contact name: " contactName
			echo
			./RmBiz 2 $contactName
			;;
		3)	# Re-run the Menu script
			./Menu
			;;
		0)	#
			menu=false # This allows the script to exit the while loop
			echo
			echo "Goodbye!"
			echo
			exit 0
			;;
		*)	# Catches any invalid user input
			echo
			echo "Invalid input. Please enter a number between 0 & 3."
			;;
		esac
	done
	;;
3)	echo
	echo "Please search for business name, number, address, email, etc: "
	read find
	./FindBiz $find
	;;
4)	# Run a sub-menu for emailing contacts. It is enclosed in a while loop
        # to allow it to be reloaded repeatedly if the user's input is invalid.
        menu=true
        while [ $menu == true ]
        do
		echo
		echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "E M A I L    M E N U"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "1) Search for business to email"
		echo "2) Email all businesses"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "3) Return to main menu"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        echo "0) Exit"
	        echo "~~~~~~~~~~~~~~~~~~~~"
	        read -p "Menu choice: " option3

	        case $option3 in

		1)	subMenu=true
			while [ $subMenu == true ]; do
			echo
			#read in search term
			echo "Please enter the business name, contact name, email address, etc: "
			read search
			matches=$(grep -i "$search" BusinessDetails) # returns entrys with a matching string
			inputCount=$(echo "$matches" | grep -ci "$search") #count results from grep and store in variable

			if [ $inputCount -gt 1 ]; then # if there are multiple matches
				echo
				echo "Your search returned multiple records."
				echo
				echo "Would you like to email one of these businesses?"
		                echo "~~~~~~~~~~~~~~~~~~~~"
		                # While loop to create numbered menu based on the number of entries returned by the user search
		                count=1 # variable to increment up to value of $inputCount
		                while [ $count -le $inputCount ]; do
		                        menuLine=$(echo "$matches" | sed -n "${count}p") # stores individual record in menuLine variable
		                        newL=$'\n' # line break variable to use below
		                        menuLines+="$count) $menuLine$newL" # concats numbered menu lines w/ line breaks
		                        selectFrom+="count$count $menuLine$newL" # creates separate list with "count" term at start to make selection of the correct line more robust
		                        ((count++)) # increments count variable
		                done
		                echo "$menuLines" | column -t -s $'\t' -n # displays options w/ column layout
		                echo "~~~~~~~~~~~~~~~~~~~~"
		                mainMenOption=$(($inputCount + 1)) # Return to main menu value dynamically created
		                echo "$mainMenOption) Return to Main Menu"
		                echo "~~~~~~~~~~~~~~~~~~~~"
		                echo "0) Exit"
		                echo "~~~~~~~~~~~~~~~~~~~~"
		                read -p "Menu choice: " choice

				if [ $choice -eq  $mainMenOption ] 2> /dev/null
		                then
		                        #subMenu=false
		                        ./Menu
		                elif [ $choice -eq 0 ] 2> /dev/null
		                then
		                        #subMenu=false
		                        echo
		                        echo "Goodbye!"
		                        echo
		                        exit 0
		                elif [ $choice -lt $mainMenOption ] 2> /dev/null
		                then
		                        #subMenu=false
		                        echo
		                        echo "Is this the business you would like to email?"
		                        echo
		                        if [ $choice -lt 10 ]; then
		                                chosenEntry=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$choice" | cut -c 8-)
		                                echo "$choice) $chosenEntry"
		                        elif [ $choice -lt 100 ]; then
		                                chosenEntry=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$choice" | cut -c 9-)
		                                echo "$choice) $chosenEntry"
		                        else
		                                chosenEntry=$(echo "$selectFrom" | column -t -s $'\t' -n | grep "count$choice" | cut -c 10-)
		                                echo "$choice) $chosenEntry"
		                        fi
					echo
					read -p "(y/n): " sureEmail

					if [[ $sureEmail == y* || $sureEmail == Y* ]]; then
						emailAddress=$(echo "$chosenEntry" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
						echo
						echo "Please enter the email subject line: "
						read subject
						echo
						echo "Please enter the email message: "
						read message
						echo "$message" | mail -s $subject $emailAddress
						echo
						echo "Message sent to $emailAddress."
						echo
						subMenu=false
	                        	else
	                                	echo
	                                	echo "Would you like to perform another search? (y/n): "
						read ans4
	                                	echo
						if [[ $ans4 == y* || $ans4 == Y* ]]; then
							subMenu=true
						else
							subMenu=false
							echo
							echo "Would you like to return to the main menu? (y/n): "
							read ans5
							echo
							if [[ $ans5 == y* || $ans5 == Y* ]]; then
								./Menu
							else
								echo
								echo "Goodbye!"
								echo
								exit 0
							fi
						fi
					fi
				else
					echo
		                        echo "Invalid input. Please enter a number between 0 & $mainMenuOption."
                		        echo
				fi
			elif [ $inputCount -eq 1 ]; then
	                        echo
				echo "Your search returned the following record."
				echo
				echo "Would you like to email this business?"
				echo "~~~~~~~~~~~~~~~~~~~~"
	                        echo
	                        singleResultMenu=$'Business Name\tContact Name\tAddress\tPhone Number\tEmail Address\n----------\t---------\t----------\t----------\t----------\n'
	                        singleResultMenu+="$matches"
	                        echo "$singleResultMenu" | column -t -s $'\t' -n
				echo
                                read -p "(y/n): " sureEmail

                                if [[ $sureEmail == y* || $sureEmail == Y* ]]; then
                                        emailAddress=$(echo "$matches" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
                                        echo
                                        echo "Please enter the email subject line: "
                                        read subject
                                        echo
                                        echo "Please enter the email message: "
                                        read message
                                        echo "$message" | mail -s $subject $emailAddress
                                        echo
                                        echo "Message sent to $emailAddress."
                                        echo
                                        subMenu=false
					./Menu
				else
					echo
                                        echo "Would you like to perform another search? (y/n): "
                                        read ans4
                                        echo
                                        if [[ $ans4 == y* || $ans4 == Y* ]]; then
                                                subMenu=true
                                        else
                                                subMenu=false
                                                echo
                                                echo "Would you like to return to the main menu? (y/n): "
                                                read ans5
                                                echo
                                                if [[ $ans5 == y* || $ans5 == Y* ]]; then
                                                        ./Menu
                                                else
                                                        echo
                                                        echo "Goodbye!"
                                                        echo
                                                        exit 0
                                                fi
                                        fi
				fi
			else
                                echo
				echo "Your search didn't return any results."
				echo
                                echo "Would you like perform another search? (y/n): "
                                read ans5
                                echo
                                if [[ $ans5 == y* || $ans5 == Y* ]]; then
                                        subMenu=true
                                else
					subMenu=false
					echo
                                        echo "Would you like to return to the main menu? (y/n): "
	                                read ans5
        	                        echo
                	                if [[ $ans5 == y* || $ans5 == Y* ]]; then
                        	                ./Menu
                                	else
                                        	echo
	                                        echo "Goodbye!"
        	                                echo
                	                        exit 0
                        	        fi

                                fi
			fi
			done
			;;
		2)	echo
			echo "Please enter the email subject line: "
                        read subject
                        echo
                        echo "Please enter the email message: "
                        read message
                        echo
			echo "Are you sure you want to send this message to all your contacts?"
			echo
			echo "SUBJECT: $subject"
			echo "----------"
			echo "MESSAGE: $message"
			echo
			read -p "(y/n): " sureEmail
			if [[ $sureEmail == y* || $sureEmail == Y* ]]; then
				bizNum=$(wc -l < BusinessDetails)
				count=1
				while [ $count -le $bizNum ]; do
					emailAddress=$(sed -n "${count}p" BusinessDetails | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
					echo "$message" | mail -s $subject $emailAddress 2> /dev/null # dumps errors for invalid email addresses
					((count++))
				done
				echo
                        	echo "Message sent to all contacts."
                        	echo
                        	menu=false
                        	./Menu
			fi
			;;
		3) 	menu=false
			./Menu
			;;
		0)	menu=false
			echo
			echo "Goodbye!"
			echo
			exit 0
			;;
		*)	echo
	        	echo "Invalid input. Please enter a number between 0 & 4."
			echo
			;;
		esac
	done
	;;
0)	echo
	echo "Goodbye!"
	echo
	exit 0
	;;
*)	#
	echo
        echo "Invalid input. Please enter a number between 0 & 4."
	./Menu
	;;
esac

exit 0


