#!/bin/bash
# Author: Kent Chadwick
# Description: Removes business entries based on user input of business name or contact name
#
# if statement determines if the user is searching for Business or Contact name via $1
if [ $1 -eq 1 ]; then
	input=$(awk -F " ; " '{print $1}' BusinessDetails | grep -i $2 | sort)
else
	input=$(awk -F " ; " '{print $2}' BusinessDetails | grep -i $2 | sort)
fi

# Count the number of entries that match the user's search input, and store the value in $inputCount
inputCount=$(echo "$input" | grep -ci $2)

# Display different options depending on the value of $inputCount
if [ $inputCount -eq 0 ]
then
	echo "Your search didn't match any records in our address book."
	echo "Would you like to search again? (y/n)"
	read ans1
	if [[ $ans1 == y* || $ans1 == Y* ]]
	then
		echo
		./RmBiz
	else
		echo
		echo "Good bye!"
		echo
		exit 0
	fi
elif [ $inputCount -gt 1 ]
then
	echo "Your search matched multiple records."
	echo
	echo "Which record would you like to remove?"
	echo "~~~~~~~~~~~~~~~~~~~~"
	# While loop to create numbered menu based on the number of entries returned by the user search
	selectFrom=""	# Variable to store count number paired with the entry string so it can be selected from the menu option
	count=1
	while [ $count -le $inputCount ]; do
		menuLine=$(sed -n "${count}p" BusinessDetails) 
		echo "$count) $menuLine"
		newL=$'\n'
		selectFrom+="count$count ; $menuLine$newL"
		((count++))
	done
	echo "~~~~~~~~~~~~~~~~~~~~"
	mainMenOption=$(($inputCount + 1))
	echo "$mainMenOption) Return to Main Menu"
	echo "~~~~~~~~~~~~~~~~~~~~"
	echo "0) Exit"
        echo "~~~~~~~~~~~~~~~~~~~~"
	read -p "Menu choice: " choice
	if [ $choice -eq  $mainMenOption ]; then
		./Menu
	elif [ $choice -eq 0 ]; then
		echo
		echo "Goodbye!"
		echo
		exit 0
	else
		echo "$selectFrom" | grep "count$choice" | cut -c 10-
		
	fi
else
	echo "Your search matched the following record:"
	echo
	singleResult=$(grep -i $input BusinessDetails)
	echo $singleResult
	echo
	echo "Would you like to delete this entry? (y/n)"
	read ans2
	if [ $ans2 == "y" ]
	then
		sed -i "/$singleResult/d" BusinessDetails
		echo
		echo "Entry deleted."
		echo
	else
		echo "Would you like to perform another search? (y/n)"
		read ans3
		if [ $ans3 == "y" ]
		then
			echo
			./RmBiz
		else
			echo
			echo "Good bye!"
			echo
		fi
	fi
fi
# awk '/$input/ {print $1,$2}' BusinessDetails
# grep $input BusinessDetails
